URL = 'http://try.dbms.nil.foundation/'
DB_NAME = 'market2'
MOUNT = 'market2'
USER= 'root'
AUTH_FILE='./.auth.json'
PROOFS_DIR= './proofs/statements/'
WAIT_BEFORE_SEND_PROOF = 30
ASK_UPDATE_INTERVAL=20
MY_STATEMENTS=['1','2','3','4731458']